In [2]:
import sys

sys.path.append("/Users/hardenyu/Study/HydraNet/python")

In [3]:
import hydranet as hy

In [5]:
x = hy.ones(3, 2, 2, 3)
x

hy.Tensor([[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]])

In [4]:
import torch._tensor_str

In [35]:
import torch

x = torch.ones(3, 2, 2, 3)

In [4]:
x = hy.Tensor([1, 2, 3])

In [5]:
x

hy.Tensor([1 2 3])